project:
  type: book

book:
  title: "STAT8310 - Bayesian Data Analysis"
  author: "Chi-Kuang Yeh"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - week01.qmd
    - week02.qmd
    - week03.qmd
    - week04.qmd
    - week05.qmd
    - week06.qmd
    - week07.qmd
    - week08.qmd
    # - week09.qmd
    # - week10.qmd
    # - week11.qmd
    # - summary.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/chikuang/Teaching-Stat8310
        aria-label: GitHub
      - icon: file-pdf
        href: ./STAT8310---Bayesian-Data-Analysis.pdf
        aria-label: Download PDF

bibliography: references.bib

execute:
  cache: true
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: custom-callouts.css
    filters: []
    cache: true
  pdf:
    documentclass: scrreprt
    filters: []
    cache: true

editor: visual